import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Mini App Next.js",
  description: "Generated by create next app",
};

const roboto = Roboto({ subsets: ["vietnamese"], weight: ["100", "300", "400", "500", "700", "900"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <h1>Auth</h1>
      <div>
        <Link href={'/'}>Login</Link>
      </div>
      <body className = {roboto.className}>{children}</body>
    </html>
  );
}
