import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Mini App Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className="mdl-js">
      <body
      
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="max-w-4xl mx-auto p-4">
          <header className="mb-6">
            <h1 className="text-4xl font-bold text-blue-600">Mini App</h1>
            <nav className="mt-4">
              <a href="/" className="text-blue-600 hover:underline mr-4">
                Trang chủ
              </a>
              <a href="/blog" className="text-blue-600 hover:underline mr-4">
                Blog
              </a>
              <a href="/blog/tech" className="text-blue-600 hover:underline">
                Công nghệ
              </a>
            </nav>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
